"""initial_schema

Revision ID: eebf04727465
Revises:
Create Date: 2026-08-24 12:40:38.572301

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eebf04727465"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("api_key_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_merchants_email"), ["email"], unique=True)

    op.create_table(
        "checkout_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checkout_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_checkout_sessions_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_checkout_sessions_status"), ["status"], unique=False)

    op.create_table(
        "merchant_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("max_autonomous_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("daily_limit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("allowed_categories", sa.JSON(), nullable=True),
        sa.Column("max_delivery_days", sa.Integer(), nullable=True),
        sa.Column("min_return_days", sa.Integer(), nullable=True),
        sa.Column("approval_threshold", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("merchant_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchant_policies_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "sku", name="uq_product_merchant_sku"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_merchant_id"), ["merchant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=False)

    op.create_table(
        "purchase_intents",
        sa.Column("intent_id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("max_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("allowed_category", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
    )
    with op.batch_alter_table("purchase_intents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_intents_merchant_id"), ["merchant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_purchase_intents_status"), ["status"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("checkout_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_checkout_id"), ["checkout_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_merchant_id"), ["merchant_id"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("checkout_id", sa.String(length=36), nullable=False),
        sa.Column("merchant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_checkout_id"), ["checkout_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_orders_merchant_id"), ["merchant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)

    op.create_table(
        "product_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("price_override", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_variants_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_product_variants_sku"), ["sku"], unique=True)

    op.create_table(
        "checkout_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("checkout_id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkout_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checkout_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_checkout_items_checkout_id"), ["checkout_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_checkout_items_variant_id"), ["variant_id"], unique=False
        )

    op.create_table(
        "inventory",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("available_qty", sa.Integer(), nullable=False),
        sa.Column("reserved_qty", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_variant_id"), ["variant_id"], unique=True)

    op.create_table(
        "payments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("razorpay_order_id", sa.String(length=128), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_order_id"), ["order_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_payments_razorpay_order_id"), ["razorpay_order_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payments_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_status"))
        batch_op.drop_index(batch_op.f("ix_payments_razorpay_order_id"))
        batch_op.drop_index(batch_op.f("ix_payments_order_id"))

    op.drop_table("payments")
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_variant_id"))

    op.drop_table("inventory")
    with op.batch_alter_table("checkout_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checkout_items_variant_id"))
        batch_op.drop_index(batch_op.f("ix_checkout_items_checkout_id"))

    op.drop_table("checkout_items")
    with op.batch_alter_table("product_variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_variants_sku"))
        batch_op.drop_index(batch_op.f("ix_product_variants_product_id"))

    op.drop_table("product_variants")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_merchant_id"))
        batch_op.drop_index(batch_op.f("ix_orders_checkout_id"))

    op.drop_table("orders")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_merchant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_checkout_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("purchase_intents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_intents_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_intents_merchant_id"))

    op.drop_table("purchase_intents")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_sku"))
        batch_op.drop_index(batch_op.f("ix_products_merchant_id"))
        batch_op.drop_index(batch_op.f("ix_products_category"))

    op.drop_table("products")
    with op.batch_alter_table("merchant_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_policies_merchant_id"))

    op.drop_table("merchant_policies")
    with op.batch_alter_table("checkout_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_checkout_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_checkout_sessions_merchant_id"))

    op.drop_table("checkout_sessions")
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_email"))

    op.drop_table("merchants")
    # ### end Alembic commands ###
